@startuml AAD Example
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(weba, "Website A") {
    Container(frontend, "Frontend", "Cookie Auth", "")
    Container(bff, "Backend For Frontend", "OAuth", "")
}

System(webb, "Website B", "SPA")

System_Boundary(apia, "API A") {
    Container(webapia, "API A", ".Net Core API")
    Container(scheduler, "Job Scheduler", ".Net Core/Hangfire")
}

System(apib, "API B", ".Net Core API")

Rel(frontend, bff, "Open ID Connect Sign In")
Rel(bff, webapia, "Authorization code flow")
Rel(webb, webapia, "Authorization code flow (with PKCE)")
Rel(webapia, apib, "On behalf of")
Rel(scheduler, apib, "Client credentials")

@enduml